

function getBotResponse(input) {
    //responses for button click questions
    if (input == "What confidence can we place in the counsellors here?") {
        return "All counsellors here will have the opportunity to post advertisements after a special qualification test conducted by us. Therefore, there should be no doubt about the qualifications of the counsellors.";
    } else if (input == "Is there an opportunity to submit a pre-made CV when applying for a job?") {
        return "It is essential for a job seeker to submit a CV generated by this website when applying for a job.";
    } else if (input == "What are the benefits and specialities of job posting on this site?") {
        return "There is no charge for the initial 10 ads you post by the company or for the initial three months of posting the ads.";
    }else if (input == "Will the job advertisement be removed from the website without prior notice when the agreed time limit for a job vacancy has passed?") {
    return "The company will be notified by e-mail shortly before the expiration date of the advertisement.";
    } else if (input == "What is the charge for posting a job vacancy?") {
    return "It mainly depends on the duration of the advertisement being displayed on the website.";
    }

    // Simple responses
    if (input == "hello" || input == "Hello" ) {
        return "Hello there!";
    } else if (input == "hi" || input == "Hi" ) {
        return "Hi there!";
    } else if (input == "hey" || input == "Hey" ) {
        return "Hey there!";
    } else if (input == "goodbye" || input == "Goodbye" || input == "Good bye" || input == "good bye" || input == "Good Bye" ) {
        return "Talk to you later!";
    } else {
        return "Try asking something else! Or Click here to connect with Contact US";
    }
}